language: python
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get install libcfitsio3-dev python-matplotlib python-pyfits
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-2.0.0-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-2.2.2-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
# command to install dependencies
install: 
  - conda install --yes pip numpy cython astropy setuptools matplotlib
  - pip install --use-mirrors pyfits
  - pip install -r requirements.txt --use-mirrors
  - python setup.py install
# command to run tests
script:
  - bash travistest.sh
notifications:
  email: false
